"""empty message

Revision ID: 371cea31d4bc
Revises: 
Create Date: 2017-10-27 21:41:19.901220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371cea31d4bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('aname', sa.String(), nullable=True),
    sa.Column('asex', sa.String(), nullable=True),
    sa.Column('aphone', sa.String(), nullable=True),
    sa.Column('aremark', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ano')
    )
    op.create_table('medicines',
    sa.Column('mno', sa.Integer(), nullable=False),
    sa.Column('mname', sa.String(), nullable=True),
    sa.Column('mmode', sa.String(), nullable=True),
    sa.Column('mefficacy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mno')
    )
    op.create_table('clients',
    sa.Column('cno', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(), nullable=True),
    sa.Column('csex', sa.String(), nullable=True),
    sa.Column('cage', sa.Integer(), nullable=True),
    sa.Column('caddress', sa.String(), nullable=True),
    sa.Column('cphone', sa.String(), nullable=True),
    sa.Column('csymptom', sa.String(), nullable=True),
    sa.Column('cdate', sa.DateTime(), nullable=True),
    sa.Column('cremark', sa.String(), nullable=True),
    sa.Column('mno', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ano'], ['agencies.ano'], ),
    sa.ForeignKeyConstraint(['mno'], ['medicines.mno'], ),
    sa.PrimaryKeyConstraint('cno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('medicines')
    op.drop_table('agencies')
    # ### end Alembic commands ###
